version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bodymetrics123
      POSTGRES_DB: bodymetrics
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:bodymetrics123@db:5432/bodymetrics
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data: